### PR TITLE
Mobile header

### PR DESCRIPTION
**Pull request by davidbgomes**
Clickup task: [Implement Mobile menu](https://app.clickup.com/t/865cnmg2r)

image

Create Mobile Header component for tablet or less viewports

### CODE REVIEW

**Review by xurxodev — CHANGES_REQUESTED** [review]
thanks @davidbgomes 

Using material UI we should avoid to use exact media queries. As I already told you in the last follow-up meeting, please review the malaria threat map solution in home page for change between desktop menu and mobile menu

**Comment by xurxodev** [comment]
@davidbgomes please add task to the PR description

**Comment by xurxodev** [comment]
> > thanks @davidbgomes
> > Using material UI we should avoid to use exact media queries. As I already told you in the last follow-up meeting, please review the malaria threat map solution in home page for change between desktop menu and mobile menu
> 
> Thank you @xurxodev can you explain why it's not a good approach to use media queries for that? Anyhow, I've tried that approach with the `Hidden` component with `lgUp` and `lgDown` for each but leads to some weird behaviours, at least on my end. Some breakpoints don't show anything.

@davidbgomes Using the material UI, we should use sizes (lg, md, etc.), in the future we could modify the values for each size, then only the places where we use sizes will affect the change. Places, where we use exact media queries, would be error prone and manually search and quite possibly forget.

**Comment by davidbgomes** [comment]
@xurxodev I see, thanks for the explanation and makes sense. It's just that the Hidden component seems buggy to me, it simply doesn't show any content on my regular screen size, hides both the lgUp and lgDown.. I can do it with the md breakpoint, that one seems to be working more accurately.

**Comment by davidbgomes** [comment]
@xurxodev I've applied the Hidden component with the md breakpoint.

**Comment by anagperal** [comment]
@davidbgomes I've added a comment in the code to review about mdDown🙏

**Comment by saragilcas** [comment]
@xurxodev I'm merging this for now and we can revisit it if needed.

**Pull request merged**
