### PR TITLE
Policy explorer: add Changes in coverage policy since 2020 and Changes in coverage policy up to and including 2019

### PR DESCRIPTION
**Pull request by anagperal**
### :pushpin: References

-   **Issue:** Closes [Policy Changes - Policy Explorer Design](https://app.clickup.com/t/865ccndf4)

### :memo: Implementation

- [x] Add Changes in coverage policy up to and including 2019 new section
- [x] Add Changes in coverage policy since 2020 new section
- [x] Allow also get dataElements of valueType "TEXT" only if are from one of  the two added sections
- [x] Year of section Changes in coverage policy up to and including 2019: from 2000 to 2019. (these years with their corresponding data must be shown in the table)
- [x] Years of section Changes in coverage policy since 2020: from 2020 until current year. (these years with their corresponding data must be shown in the table)
- [x] Years of all other sections: only current year. (only this year with their corresponding data must be shown in the table)
- [x] Do not display the row when there is no data in any cell
- [x] Do not display the column when there is no data in any cell
- [x] Tests repository and component
- [X] Refactor Policy Explorer Repository adding TableBuilder

### :art: Screenshots

2023-08-10 17_33_19-UHC watch

Without the rows with no data:

Without the rows with no data and the columns with no data:
2023-08-31 13_36_54-UHC watch

### CODE REVIEW

**Comment by xurxodev** [comment]
@saragilcas @anagperal I try to review this PR, but I think that I need context to understand well the task previously and the metadata in this case. We can to talk in the next meeting

**Comment by anagperal** [comment]
sure @xurxodev! it's better to talk about this 3 PRs (https://github.com/EyeSeeTea/uhcpw/pull/106, https://github.com/EyeSeeTea/uhcpw/pull/105, https://github.com/EyeSeeTea/uhcpw/pull/104) because implies some changes that are perhaps best explained by talking about. (cc @saragilcas)

**Comment by anagperal** [comment]
@xurxodev the refactors discussed [here ](https://github.com/EyeSeeTea/uhcpw/pull/104#pullrequestreview-1610567372) are ready for review

**Review by xurxodev — APPROVED** [review]
thanks @anagperal 

Great refactor work, congratulations!

**Pull request merged**
