### PR TITLE
Reset filters on leave, ui improvements, single filter behaviour

### PR DESCRIPTION
**Pull request by davidbgomes**
Related to issue: [Implement search for glossary](https://app.clickup.com/t/865cqzth3)

- Reset filters on close;
- UI improvements (font using typography variants);
- Single filter behaviour (when using text search, reset the letter filter & vice-versa).

image

### CODE REVIEW

**Comment by anagperal** [comment]
Hi @davidbgomes ! It works perfect :tada: but you have to be careful about resetting the letters filter to `"All"`.
If you look at the hook src\webapp\pages\about\useAbout.ts, you can see that all filter is `const allFilter = i18n.t("All");` and it changes according with the translation so for other languages it would not work. Maybe you can export allFilter variable and use it instead of directly using `"All"`.

**Review by anagperal — CHANGES_REQUESTED** [review]
Hi @davidbgomes ! It works perfect :tada: but you have to be careful about resetting the letters filter to `"All"`.
If you look at the hook src\webapp\pages\about\useAbout.ts, you can see that all filter is `const allFilter = i18n.t("All");` and it changes according with the translation so for other languages it would not work. Maybe you can export allFilter variable and use it instead of directly using `"All"`.

**Comment by davidbgomes** [comment]
Thank you @anagperal ! Totally makes sense, I've exported and used the allFilters variable instead of the "all" literal.

**Review by anagperal — APPROVED** [review]
@davidbgomes thanks!!

**Comment by saragilcas** [comment]
Thanks @davidbgomes looks great

**Pull request merged**
