### PR TITLE
Country page: slider

### PR DESCRIPTION
**Pull request by davidbgomes**
Related to issue: [Country page: slider](https://app.clickup.com/t/865craupc)

- Implement slider changing steps on mouse scroll (when hovering tabs)

### CODE REVIEW

**Review by anagperal — COMMENTED** [review]
Works perfect! :tada: Just small comment, you can join internal and external ifs together instead of having one inside the other in onWheel function

**Comment by davidbgomes** [comment]
Thank you @anagperal ! Good point, just fixed that and deleted the unnecessary ifs :)

**Comment by saragilcas** [comment]
@davidbgomes & @anagperal I have merged this one as a first approximation :) but I am pretty sure that the client was thinking of something more along these lines: https://scrollmagic.io/examples/advanced/section_slides_manual.html 

That is to say, independently of where your mouse cursor is, once you are on the slider div, when you scroll down with the mouse the slides change automatically. Would it be too difficult to implement? Maybe we can wait because I know they want to make changes to the design of this page.

**Comment by davidbgomes** [comment]
@saragilcas sounds good! No, it shouldn't be too dificult, but in that case we have to be aware that depending on the height of slider and user's viewport, the users could be "trapped" inside the slider trying to scroll the normal content. Just something to consider for the ux.

**Comment by saragilcas** [comment]
> @saragilcas sounds good! No, it shouldn't be too dificult, but in that case we have to be aware that depending on the height of slider and user's viewport, the users could be "trapped" inside the slider trying to scroll the normal content. Just something to consider for the ux.

Thanks @davidbgomes we are going to wait to see what happens. I had clients before requesting this kind of effect and I have to say I don't like it too much :D

**Pull request merged**
